#! /usr/bin/env bash

if [ $# -eq 0 ]; then
       echo 'Usage: ./teams "<title>" "<message>"'
       exit 1
fi

#WEBHOOK_URL=<your_teams_channel_webhook_here>
TITLE=$1
shift
TEXT=$*

# Convert formating.
MESSAGE=$( echo ${TEXT} | sed 's/"/\"/g' | sed "s/'/\'/g" )
JSON="{\"title\": \"${TITLE}\", \"text\": \"${MESSAGE}\" }"

# Post to Microsoft Teams.
curl -H "Content-Type: application/json" -d "${JSON}" "${WEBHOOK_URL}"
